### ISSUE TITLE
Build problem (perhaps because I'm newbie)

### ISSUE THREAD

**Issue by bjornfor** [Fuuzetsu/jenkinsPlugins2nix#1]
Hi, I tried to build the project and got this:

```
$ git clone https://github.com/Fuuzetsu/jenkinsPlugins2nix.git
$ cd jenkinsPlugins2nix
$ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hnix-0.3.4:
    data-fix-0.0.4 must match >=0.0.7 (latest applicable is 0.2.0)
needed due to jenkinsPlugins2nix-0.2.0.2 -> hnix-0.3.4

Plan construction failed.
```

This is on NixOS 17.03. Any easy fix? For now I'm using ```nix-build -A haskellPackages.jenkinsPlugins2nix```, which works, but I'd like to try hacking too :-)

**Comment by Fuuzetsu** [comment]
Hi. The problem is that the package dependencies were changed on Hackage without bumping version. See:

https://hackage.haskell.org/package/hnix-0.3.4/revisions/

With sufficiently recent stack, you can make the following change:

```
modified   stack.yaml
@@ -3,7 +3,7 @@ resolver: lts-8.14
 packages:
   - '.'
 extra-deps:
-  - hnix-0.3.4
+  - hnix-0.3.4@rev:0
 
 flags: {}
```

and things should start working again.

Apologies for late reply.

**Comment by bjornfor** [comment]
Ah, I see. The default "stack" on NixOS 17.03 is apparently too old:

```
$ stack build
Could not parse '/home/bfo/proj/code/forks/jenkinsPlugins2nix/stack.yaml':
Aeson exception:
Error in $['extra-deps'][0]: failed to parse field 'extra-deps': (Invalid package identifier: "hnix-0.3.4@rev:0","hnix-0.3.4@rev:0")
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

Perhaps I'll come back later to hack on jenkinsPlugin2nix :-)
