### ISSUE TITLE
Manage package maintenance

### ISSUE THREAD

**Issue by fuzzy-id** [Fuuzetsu/jenkinsPlugins2nix#6]
Noticed that there isn't much happening in this respository for quite some time. The tool is still used by a couple of people though. I forked it a while ago and am willing to do some maintenance. (Mainly verison bumps, making it compile on recent versions of NixOS.) It would be nice to have this reflected on hackage. Any preferences on your side on how to manage this? (See https://wiki.haskell.org/Taking_over_a_package for a couple of options.)

**Comment by Fuuzetsu** [comment]
Right, I haven't been using this package myself at all since I initially wrote it so it's just been very low on priority list which is why there are a couple of basically ready-to-go PRs outstanding. I'm happy to add a maintainer on Hackage and GitHub. What's your Hackage handle?

**Comment by fuzzy-id** [comment]
Sorry for the delay. Just created a hackage account: `ThomasBach` it is.

**Comment by Fuuzetsu** [comment]
I have added you on Hackage. You should have commit rights on the repository already. Thanks.
